<?php
/**
 * @file library_environment.module
 * TODO: Enter file description here.
 */




/**
 * Implementation of hook_environment_switch().
 */
function library_environment_environment_switch($target_env, $current_env) {
  // Declare each optional development-related module
  $devel_modules = array(
    'search_api_local',
  );
  $staging_modules = array(
    'search_api_staging',
    );
  $production_modules = array(
    'search_api_production',
    );

  switch ($target_env) {
    case 'production':
      module_disable(array_merge($devel_modules, $staging_modules));
      module_enable($production_modules);

      drupal_set_message('Disabled development modules');
      return;
    case 'development':
      module_disable(array_merge($production_modules, $staging_modules));
      module_enable($devel_modules);


      drupal_set_message('Enabled development modules');
      return;
    case 'staging':
      module_disable(array_merge($production_modules, $devel_modules));
      module_enable($staging_modules);
      drupal_set_message('Enabled development modules');
      return;
  }

}
